services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: snippetbox
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: